apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  ports:
    - protocol: TCP
      name: phpmyadmin
      port: 5000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_img
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
